### ISSUE TITLE
A little confusion about sets.add method

### ISSUE THREAD

**Issue by chengfulin** [wala/JS_WALA#4]
Hello, I was confused when read on the add method of sets module after tracing the use from the addEdge function in the cfg module.
I cannot figure out in which condition the last return statement would occur?

Thanks for your response.
Sincerely yours.

**Comment by xiemaisi** [comment]
You mean this line: https://github.com/wala/JS_WALA/blob/master/common/lib/sets.js#L55 ?

**Comment by msridhar** [comment]
Assuming you're talking about the line @xiemaisi linked, this is for the case when the `set` argument is a singleton.  In this case, the representation of the set is the contained element itself, and the last return statement handles adding a new element `elt`.

**Comment by chengfulin** [comment]
Thanks you.
I found that I was not cleared about what the representation of singleton
is.
After reviewed and thought for a while, I could understand it.

2015-03-28 5:25 GMT+08:00 Manu Sridharan <notifications@github.com>:
